server:
  #  ssl:
  #    enabled: true
  #    key-store: classpath:keystore.p12
  #    key-store-type: PKCS12
  #    key-store-password: abc123456
  jetty:
    threads:
      selectors: 4
      acceptors: 8
      min: 8
      max: 200
  port: 7900
  servlet:
    context-path: /api

spring:
  redis:
    database: 0
    host: redis
    port: 6379
    password: abc123456
    lettuce:
      pool:
        max-active: 1400
        max-wait: -1ms
        max-idle: 24
        min-idle: 15
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  #      exclude: WEB-INF/**
  data:
    mongodb:
      host: mongo
      port: 27017
      username: mongo
      password: abc123456
      authentication-database: admin
      database: his
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:7001/his?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: abc123456
      initial-size: 8
      max-active: 16
      max-wait: 60000
      #    driver-class-name: com.mysql.cj.jdbc.Driver
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      validation-query: SELECT 1
  #    hikari:
  #      minimum-idle: 5   # 最小空闲连接数量
  #      idle-timeout: 180000   #  空闲连接存活最大时间，默认600000（10分钟）
  #      maximum-pool-size: 20 # 连接池最大连接数，默认是10
  #      auto-commit: true # 控制从池返回的链接的默认自动提交行为，默认值：true
  #      pool-name: Hikari # 连接池名称
  #      max-lifetime: 1800000 # 控制池中链接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
  #      connection-timeout: 30000 # 数据库链接超时时间，默认30秒，即30000
  #      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
      enabled: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.Yu.his.service.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    com.Yu.his.service.mapper: info
knife4j:
  basic:
    enable: true
sa-token:
  #   过期时间(秒),30天
  timeout: 2592000
  #    临时有效期
  activity-timeout: 259200
  #    HTTP请求头中哪个属性哪个是属性用来上传令牌
  token-name: token
  #不允许多点登录
  #    在多人登录相同账号时,是否使用相同的token
  is-share: false
  token-style: uuid
  is-read-cookie: false
  #    同端互斥
  isConcurrent: false

alipay:
  app_id: 9021000132603149
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCOoN2ZFAlTFbbu6NEsMeUGM9ISQh9rrPQBDMD0ghme5R1Uu8bko7XAY89wLG7adYRD5dgyR8/dMwTzRUPk/WBtWp+bmIo/YqsszbBxD7I13dC/X0MCykRTEZSZ219isbKVZf86jjipd0qxXTHI6tDWAizBanjRz1nCv4uXchXHA+hJYiyBid6c+DqReXrz2NFBy7ToRmpmIDJZMgpKwCiA4P/vigwF0GqtQOlTcBpOZ31t9/bAFQ75y/+yEyO36yUlt5U0SH0o6paZNCwyYDNE1OaFOe6zxXnXkPqoW2c+G5yBZVv2sFR/3QI6/VOk++pF9hRZez+auDwGT0A40lVvAgMBAAECggEAESoc4QI/SQdw93l/StFKXZ+45Ued3mh3CPVO91381Vl/WSYr/nIROnEIkthWEuZXn5A2n35y7ozoSJqKXDF9/EsOsDwATzaBoSez1zdrW/4w1AcT2m8bH+AawRVcelUmR8J5n8Nj4Ekh7QxpJGPV9BtY5YH5vk404DILC5PIOSX56aEVvl2YJ/O17be/tMHKa4HQc1tsOMNSMdYhq7m9QNkSwNyHZ1xtpYy4k/sPr5Cs6n1ajS5Bx0ySFtk2OUkmxQ9AgzkTZdXBCYoP/krlPMcwpD/BiEW8V/llFzWFkz4QFOvAbJwtMmxfizDTgrL5irfXm9fXcZimA2OCdpqRwQKBgQDXSBxMdUAkQ9hUXncul0bvxukCAaVJRFI9CThCIrFgtqUAObznQO1+OItMlpqpaa10nXuqrImiT/PPtOgJ05ubnDtKD7PjMMxp7/rcnqdllaZnhsJPTQ3QrymyExwi8ecZK/b9xTD1sasCqJ+Gq/m9C7ICcqI43NXnxfx8LaKZ4QKBgQCpmuYknj4n4LU+miwn7UDscPplF6VUik2eanvTliTBaLfwMncWbQ8qEBOCruNosY93O5b6CVOQk7JLujJelxy86XbrV674VDKYUPdOM8c68zuxa5RroQlfCDaPrg7Ygr9DMkBlQe86f1XNFJw6X4dxf2wlQdjB4hKCmctalRn5TwKBgCEzSsHz1yeAmw0v4Ft8EwGJgIfBrzbkZXZqRJXWedp7cGjffqV/WuD7YWg3VbTIympQmzDQGQ3CHMysjphtXPMbnf0m/MwNy4iO7PY3NYOyF46htre6H2ZOjTScQ9uTyNsV76plTc6mTsRDMw722LXx5sr/2MrCK+7plq2j8A6hAoGAQG/UTkc8sCPkWEN00TqHdw05ZJ0GOEdPVAd6whmCH2UstPpHWmLW5xEyiGzvg0AqlI80Pgy7Deu/SpwUNPHOfkto3eLzW++JRWtFehWb9N6iaDbKLdYB3HQfXpkvlLyf8+SsqIvTWvMz4vWYoWjX6ZwSt1j8BDVi+PF7XA/XzWsCgYAw5ETDEmT1skKx+2DI2hdoXiK0ZYwUJ4JmTmSOHlFGAIwZkVH3Kr+ONqBXJwbd0/qY2ST59z3D6fybZyhcemIFW95NZMFiZYAcPGXL/YdPgsOqYSY9f8DWPBAupjU9nFutIK+6Yer4zzSTaFBbQAmlA/U1PtGskhXZUyxtO0gPBQ==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjd/BMIzojT7yr7Y0bFIbXNM3T7DRQLOKvk/Z+pOh1KsEuoQyx1xGeHO/vRbIS/TfQvWJDa5q6jfkTwnyIykWy7q+yazbfJ9SSW+tgXR1S7cUw+rAVUQFNIrgem/nzsRQVSf4IGR/CsoC2yvIiQD0bJhAo9PIgwJd+WLE8GIzBdFeMeg2+OldKywEqhHo7Bws6MFMKyW5r9P+laSYANkEItcjSio37Snc2FePf+1ZsNM+X2XkCMjhI8807si9fBqNzXQrvX6RGIakFcfpv8vkp3ZAOZ/pClEeYj7zy5f613OmVruIw3As7N99YAUrcuPT8txMKPtcHr1yiPqnZ3Yi6wIDAQAB
  notify_url: http://e7jmck.natappfree.cc/api/alipay/notify

#qlqmsy4235@sandbox.com



